사장님 회원가입 기능 구현 #14
A2jo/Foody pull request #17
Opened 2024-11-04 10:11 UTC by shushuaka

2024-11-04 11:27 UTC, TIP-Santa approved these changes
확인했습니다.

2024-11-04 11:28 UTC, JIMINJI1 approved these changes

2024-11-04 11:46 UTC, yaewon0411 requested changes
현재 dev 내용 반영해주세요~

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/service/OwnerService.java
> +    private static final String LOGIN_SUCCESS_MESSAGE = "로그인 성공";
이 메시지는 각 DTO 내에서 갖고 있어야 할 거 같습니당

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/service/OwnerService.java
> +            throw new IllegalArgumentException("이미 존재하는 이메일입니다.");
저희 서비스의 BusinessException을 사용해주세요

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/service/OwnerService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 이메일입니다."));
이 부분도 BusinessException으로 나가야 합니다

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/controller/OwnerController.java
> +    }
Autowired로 주입하면 테스트 시 mock 주입이 용이하지 않습니다 따라서 모든 클래스에서 @RequiredArgsConstructor를 통한 빈 주입을 제안합니다

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/controller/OwnerController.java
> +    }
공통 응답 포맷을 내보내기로 결정했었습니다!  ResponseEntity 내에서 ApiResult로 한번 감싸서 내보내 주세요

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/dto/req/OwnerLoginReqDto.java
> +}
유효성 검사 실패에 따른 메시지도 기재 바랍니다
특히 비밀번호는 정규 표현식이나 별도의 커스텀 Validator를 통해 검증해야 합니다

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/controller/OwnerController.java
> +    public ResponseEntity<OwnerLoginRespDto> login(@RequestBody OwnerLoginReqDto ownerLoginReqDto) {
RequestBody로 받는 객체에 @Valid가 달려있지 않으면 유효성 검사가 진행되지 않습니다 기재 부탁드려요

2024-11-04 11:46 UTC, yaewon0411 commented on src/main/java/com/my/foody/domain/owner/dto/req/OwnerJoinReqDto.java
> +    private Boolean isDeleted;
isDeleted는 클라이언트에게 받으면 안되는 필드이기 때문에 내부에서 false로 값을 고정하는 방식을 제안합니다
각 필드에 대한 유효성 메시지를 달아주세요

그리고 비밀번호는 인코딩 했을 때의 길이가 60자이기 때문에 클라이언트에서 max=60자로 요청을 받으면 인코딩 시 db에서 제한한 길이를 넘어섭니다

여기서도 비밀번호 정규표현식을 사용해주실 때 길이를 16자 이하 정도로 길이 제약을 걸어주세요

2024-11-04 22:22 UTC, gbognon25 approved these changes
확인했습니다.

2024-11-05 00:07 UTC, JIMINJI1 approved these changes
확인했습니다

2024-11-05 00:28 UTC, closed without merging